# Generated by Django 2.1.4 on 2019-02-14 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mulnum', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='often',
            new_name='number',
        ),
    ]
