# Generated by Django 2.1.4 on 2019-02-14 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mulnum', '0002_auto_20190214_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='number',
            old_name='votes',
            new_name='count',
        ),
    ]
