# Generated by Django 2.1.4 on 2019-02-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mulnum', '0004_auto_20190214_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
